# Generated by Django 5.0.4 on 2024-05-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_delete_borrowbook'),
        ('users', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
