# Generated by Django 5.0.4 on 2024-05-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('personal_identification_number', models.CharField(max_length=20, unique=True, verbose_name='Personal Identification Number')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Experience')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Librarian',
                'verbose_name_plural': 'Librarians',
            },
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('library_card_number', models.CharField(max_length=20, unique=True)),
                ('personal_identification_number', models.CharField(max_length=20, unique=True, verbose_name='Personal Identification Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Library User',
                'verbose_name_plural': 'Library Users',
            },
        ),
    ]
